### ISSUE TITLE
FileBox.toBuffer() and FileBox.toFile() might cause url type filebox uncaught exception and stop the node process

### ISSUE THREAD

**Issue by windmemory** [huan/file-box#42]
We've been through some weird behavior that `Filebox.toBuffer()` will cause process exit with error message like:
```shell
Error: write ECONNRESET
    at afterWriteDispatched (internal/stream_base_commons.js:78:25)
    at writeGeneric (internal/stream_base_commons.js:73:3)
    at Socket._writeGeneric (net.js:714:5)
    at Socket.connect (net.js:696:12)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:203:15)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:10)
```

or

```shell
Error: connect ETIMEDOUT 182.254.57.120:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
```

After some investigation, I found the reason that the error is uncaught is because we didn't listen on the error event of http request here:

https://github.com/huan/file-box/blob/ba37e49f287acfdbeada81681e71231f04fab8be/src/misc.ts#L121

So the error is not catchable when calling `FileBox.toBuffer()`

**Comment by huan** [comment]
Nice catch!

Thank you very much for making the file box more robust!

**Comment by windmemory** [comment]
You are welcome, let's close this issue since this should be resolved.
